## Data test train source split

In [1]:
# storing file names
import numpy as np 
import pandas as pd 

#src_class = input('BH/NS : ')
src_class = "TUC"
frac = 1

data = pd.read_csv('../source_list/'+src_class+'_data_clean_source_list.csv')
#data =  data.sample(frac=1)
#frac_no = int(len(data)*frac)
train_data = data.copy()
#test_data = data.iloc[frac_no:]
train_data.to_csv('../source_list/final_list/'+src_class+'_train.csv')
#display(train_data)
import os
ctg = src_class

def hr():
    print('----------------------------------------------------------------------------')

# Copy sources data to respective folders

data = pd.read_csv('../source_list/final_list/'+ctg+'_train.csv')

In [37]:
data['SRC_ID']

0      TC0001
1      TC0002
2      TC0003
3      TC0004
4      TC0005
        ...
269    TC0270
270    TC0271
271    TC0272
272    TC0273
273    TC0274
Name: SRC_ID, Length: 274, dtype: object

In [38]:
data

,Unnamed: 0,SRC_ID,A_NAME,A_NAME_ALT\n,A_RA,A_DEC,A_SOURCE_TYPE,A_SOURCE_TYPE_FLAG,B_NAME,B_RA,B_DEC,XOFFSET_
0,0,TC0001,CXOGLB J002353.9-720350,[GHE2001] W125,5.974829,-72.063922,QLX,?,2CXO J002353.9-720350,5.974992,-72.063947,0.003
1,1,TC0002,CXOGLB J002400.9-720453,[GHE2001] W58,6.003946,-72.081444,QLX,,2CXO J002400.9-720453,6.004075,-72.081474,0.003
2,2,TC0003,CXOGLB J002403.4-720451,[GHE2001] W46,6.014558,-72.081094,QLX,,2CXO J002403.5-720452,6.014684,-72.081116,0.003
3,3,TC0004,CXOGLB J002404.9-720451,[GHE2001] W37,6.020679,-72.080925,QLX,?,2CXO J002404.9-720451,6.020771,-72.080953,0.002
4,4,TC0005,CXOGLB J002408.3-720431,[GHE2001] W17,6.034604,-72.075397,QLX,?,2CXO J002408.3-720431,6.034720,-72.075417,0.002
...,...,...,...,...,...,...,...,...,...,...,...,...
269,269,TC0270,CXOGLB J002434.1-720333,[GHE2001] W193,6.142454,-72.059333,,,2CXO J002434.1-720333,6.142426,-72.059317,0.001
270,270,TC0271,CXOGLB J002434.9-720501,[GHE2001] W132,6.146125,-72.083867,,,2CXO J002435.0-720501,6.146027,-72.083838,0.003
271,271,TC0272,CXOGLB J002434.9-720501,[GHE2001] W132,6.145787,-72.083811,,,2CXO J002435.0-720501,6.146027,-72.083838,0.005
272,272,TC0273,CXOGLB J002437.1-720517,[GHE2001] W207,6.154792,-72.088042,,,2CXO J002437.1-720516,6.154886,-72.088021,0.002
273,273,TC0274,CXOGLB J002438.7-720427,[GHE2001] W206,6.161508,-72.074350,,,2CXO J002438.8-720427,6.161717,-72.074356,0.004

In [2]:
ch_names = [di.replace(' ' ,'_')[:] for di in data['B_NAME']]
a_names = [di.replace(' ' ,'_')[:]+'.csv' for di in data['A_NAME']]
src_id = data['SRC_ID']
#print(src_id)
os.system('rm -r '+ctg+'_data/train/')
os.system('mkdir '+ctg+'_data/train/')
for c,s ,a in zip(ch_names , src_id , a_names):
    try:
        src = '../data/all_data/'+ctg+'_data_all/'+c+'.csv' 
        ## adding source_id in file names
        dest = ctg+'_data/train/'+ s+'-'+c+'#'+a 
        #print('src ..' , src)
        #print('Copying' , dest)
        os.system('cp '+src+' '+dest)
    except:
        hr()
        print('check source : ' , c )
        hr()

hr()
print('TRAINING DATA STORED')

----------------------------------------------------------------------------
TRAINING DATA STORED

## Append all data in one file

In [77]:
from ipywidgets import IntProgress
from IPython.display import display

src_class = src_class

def hr():
    print('_______________________________________________________________________________________')


def to_float(d):
    temp = []
    for di in d:
        
        try:
            temp.append(float(di))
        except Exception as e:
            print(e)
            print('NaN detected resetting value')
            temp.append(np.NAN)
    temp = np.asarray(temp)
    return temp

In [78]:
set_type = 'train'
os.system('ls '+src_class+'_data/'+set_type+'/ > file_list')
file_list = pd.read_csv('file_list' , names=['names'])['names']
data = pd.DataFrame()

for file in file_list:
    data_temp =  pd.read_csv(src_class+'_data/'+set_type+'/'+file)
    ## extracting source_id from file names 
    src_id_name = file[:6]
    src_id = [src_id_name]*len(data_temp)
    src_id = np.asarray(src_id)
    data_temp.insert(0 ,'src_id' , src_id)
    src_n_name = file[29:-4].replace('_' , ' ')
    src_n = [src_n_name]*len(data_temp)
    src_n = np.asarray(src_n)



    data_temp.insert(0 ,'src_n' , src_n)
    data =  data.append(data_temp)
data = data.replace('      NaN' , np.nan).reset_index(drop=True)
data.to_csv('../raw_data/'+src_class+'_'+set_type+'.csv')
data.describe()

,index,sepn,ra,dec,obsid,obi,gti_start,gti_stop,gti_elapse,gti_mjd_obs,...,var_inter_index_s,var_inter_prob_s,var_inter_sigma_s,var_inter_index_u,acis_num,acis_hetg_num,acis_letg_num,hrc_num,hrc_hetg_num,hrc_letg_num
count,2404.000000,2404.000000,2404.000000,2404.000000,2404.000000,2404.0,2.404000e+03,2.404000e+03,2404.000000,2404.000000,...,2232.000000,2232.000000,2.232000e+03,1200.000000,2404.000000,2404.0,2404.0,2404.0,2404.0,2404.0
mean,4.757072,0.012527,6.027474,-72.081622,2609.366889,0.0,1.352075e+08,1.352433e+08,35864.308054,52378.901205,...,2.421147,0.436176,1.948239e-06,1.595000,11.504576,0.0,0.0,0.0,0.0,0.0
std,3.776095,0.103258,0.039153,0.011912,927.102420,0.0,3.122979e+07,3.123855e+07,29488.745956,361.455949,...,2.650247,0.340337,1.032318e-05,2.538309,2.051861,0.0,0.0,0.0,0.0,0.0
min,0.000000,0.000000,5.881189,-72.123750,78.000000,0.0,6.957900e+07,6.958305e+07,914.500000,51619.312480,...,0.000000,0.000000,2.868000e-08,0.000000,4.000000,0.0,0.0,0.0,0.0,0.0
25%,2.000000,0.000000,6.010455,-72.086430,2735.000000,0.0,1.497069e+08,1.497730e+08,5579.200000,52546.718280,...,0.000000,0.111000,1.291000e-07,0.000000,11.000000,0.0,0.0,0.0,0.0,0.0
50%,4.000000,0.000000,6.026598,-72.081010,2737.000000,0.0,1.497810e+08,1.498471e+08,32080.000000,52547.576010,...,3.000000,0.372000,2.221000e-07,0.000000,12.000000,0.0,0.0,0.0,0.0,0.0
75%,7.000000,0.000000,6.044488,-72.076903,3385.000000,0.0,1.500402e+08,1.500460e+08,66104.400000,52550.576600,...,5.000000,0.711000,5.617000e-07,3.000000,13.000000,0.0,0.0,0.0,0.0,0.0
max,25.000000,0.988744,6.161717,-72.040130,3387.000000,0.0,1.507593e+08,1.507653e+08,69681.800000,52558.899410,...,8.000000,1.000000,1.146000e-04,8.000000,13.000000,0.0,0.0,0.0,0.0,0.0

In [79]:
data

,src_n,src_id,index,sepn,instrument,detect_stack_id,name,ra,dec,obsid,...,var_inter_sigma_s,var_inter_index_u,var_inter_prob_u,var_inter_sigma_u,acis_num,acis_hetg_num,acis_letg_num,hrc_num,hrc_hetg_num,hrc_letg_num
0,CXOGLB J002353.9-720350,TC0001,0,0.0,ACIS,acisfJ0023544m720422_001,2CXO J002353.9-720350,5.974992,-72.06395,953,...,3.308000e-06,5.0,0.899,2.322e-05,7,0,0,0,0,0
1,CXOGLB J002353.9-720350,TC0001,1,0.0,ACIS,acisfJ0023544m720422_001,2CXO J002353.9-720350,5.974992,-72.06395,955,...,3.308000e-06,5.0,0.899,2.322e-05,7,0,0,0,0,0
2,CXOGLB J002353.9-720350,TC0001,2,0.0,ACIS,acisfJ0024178m720500_001,2CXO J002353.9-720350,5.974992,-72.06395,2735,...,3.308000e-06,5.0,0.899,2.322e-05,7,0,0,0,0,0
3,CXOGLB J002353.9-720350,TC0001,3,0.0,ACIS,acisfJ0024178m720500_001,2CXO J002353.9-720350,5.974992,-72.06395,2736,...,3.308000e-06,5.0,0.899,2.322e-05,7,0,0,0,0,0
4,CXOGLB J002353.9-720350,TC0001,4,0.0,ACIS,acisfJ0024178m720500_001,2CXO J002353.9-720350,5.974992,-72.06395,2737,...,3.308000e-06,5.0,0.899,2.322e-05,7,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399,CXOGLB J002437.1-720517,TC0273,5,0.0,ACIS,acisfJ0024178m720500_001,2CXO J002437.1-720516,6.154886,-72.08802,3385,...,7.816000e-08,NaN,NaN,NaN,10,0,0,0,0,0
2400,CXOGLB J002437.1-720517,TC0273,6,0.0,ACIS,acisfJ0024178m720500_001,2CXO J002437.1-720516,6.154886,-72.08802,3386,...,7.816000e-08,NaN,NaN,NaN,10,0,0,0,0,0
2401,CXOGLB J002437.1-720517,TC0273,7,0.0,ACIS,acisfJ0024178m720500_001,2CXO J002437.1-720516,6.154886,-72.08802,3387,...,7.816000e-08,NaN,NaN,NaN,10,0,0,0,0,0
2402,CXOGLB J002438.7-720427,TC0274,0,0.0,ACIS,acisfJ0024178m720500_001,2CXO J002438.8-720427,6.161717,-72.07436,2738,...,9.506000e-08,NaN,NaN,NaN,4,0,0,0,0,0
2403,CXOGLB J002438.7-720427,TC0274,1,0.0,ACIS,acisfJ0024178m720500_001,2CXO J002438.8-720427,6.161717,-72.07436,3385,...,9.506000e-08,NaN,NaN,NaN,4,0,0,0,0,0

In [58]:
data['src_id'].value_counts()

TC0107    16
TC0216    16
TC0215    16
TC0105    16
TC0183    13
          ..
TC0250     4
TC0080     4
TC0247     4
TC0073     4
TC0274     2
Name: src_id, Length: 274, dtype: int64

# Data Processing

## Filtering

In [59]:
flag_params = ['streak_src_flag' , 'sat_src_flag' , 'pileup_flag' , 'mstr_sat_src_flag' , ]

In [60]:
def correct_bool(arr):
    temp = []
    #print(arr)
    for a in arr:
        #print(a , type(a))
        if(type(a) == bool):
            temp.append(a)
        else:
            if(a==' TRUE' or a=='True' or a=='  NAN'):
                temp.append(True)
            elif(a=='FALSE' or a=='False'):
                temp.append(False)
            else:
                print('something wrong' , a , type(a))
    return temp

In [61]:
def to_float(d):
    temp = []
    for di in d:
        
        try:
            temp.append(float(di))
        except Exception as e:
            print(e)
            print('NaN detected resetting value')
            temp.append(np.NAN)
    temp = np.asarray(temp)
    return temp

In [62]:
data = pd.read_csv('../raw_data/'+src_class+'_'+set_type+'.csv' , index_col=0)
print('Data  Before flag filtering')
display(data.describe()[:1])
for f in flag_params:
    temp_flag = data[f]
    temp_flag = correct_bool(temp_flag)
    data[f] = temp_flag
    #print(temp_flag)
    data = data[data[f]==False]

#display(data)
data = data.dropna(how='all' , axis=1)
data = data.dropna(how='all' , axis=0)
display(data.describe()[:1])

/home/kumaran/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (230) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Data  Before flag filtering

,index,sepn,ra,dec,obsid,obi,src_rate_aper_m,src_rate_aper_lolim_m,src_rate_aper_hilim_m,src_cnts_aper_u,...,var_inter_sigma_s,var_inter_index_u,var_inter_prob_u,var_inter_sigma_u,acis_num,acis_hetg_num,acis_letg_num,hrc_num,hrc_hetg_num,hrc_letg_num
count,2404.0,2404.0,2404.0,2404.0,2404.0,2404.0,2274.0,2274.0,2274.0,2328.0,...,2232.0,1200.0,1200.0,1200.0,2404.0,2404.0,2404.0,2404.0,2404.0,2404.0

,index,sepn,ra,dec,obsid,obi,src_rate_aper_m,src_rate_aper_lolim_m,src_rate_aper_hilim_m,src_cnts_aper_u,...,var_inter_sigma_s,var_inter_index_u,var_inter_prob_u,var_inter_sigma_u,acis_num,acis_hetg_num,acis_letg_num,hrc_num,hrc_hetg_num,hrc_letg_num
count,2385.0,2385.0,2385.0,2385.0,2385.0,2385.0,2255.0,2255.0,2255.0,2309.0,...,2213.0,1182.0,1182.0,1182.0,2385.0,2385.0,2385.0,2385.0,2385.0,2385.0

take average of Band params

In [63]:
band_params = [ 'photflux_aper' ,'photflux_aper_lolim' , 'photflux_aper_hilim' , 'flux_aper' , 'flux_aper_lolim' , 'flux_aper_hilim' , 'var_index' ,'var_prob' , 'ks_prob' , 'kp_prob' ,'var_sigma' ,'var_mean' , 'var_min' ,  'var_max' , 'var_inter_index' , 'var_inter_prob' , 'var_inter_sigma' , 'flux_significance']

filters = ['_b' ,'_h' ,'_m' ,'_u' ,'_s']

combining band parameterd

In [64]:
data_band_mean = pd.DataFrame()
data_band_mean.index.name = 'name'
for param in band_params[:]:
    temp_row = [param+f for f in filters]
    data_temp = data[temp_row][:]

    data_temp_new = pd.DataFrame()
    for j in data_temp:
        data_temp_new.insert( 0 ,j ,to_float(data_temp[j].to_numpy()))
    temp_mean =  data_temp_new.mean(axis=1)
    data_band_mean.insert(0 , param , temp_mean)

display(data_band_mean)
#data_band_mean.to_csv('temp.csv')

,flux_significance,var_inter_sigma,var_inter_prob,var_inter_index,var_max,var_min,var_mean,var_sigma,kp_prob,ks_prob,var_prob,var_index,flux_aper_hilim,flux_aper_lolim,flux_aper,photflux_aper_hilim,photflux_aper_lolim,photflux_aper
name,,,,,,,,,,,,,,,,,,
0,1.586,6.801840e-06,0.745800,4.400000,0.514400,0.000461,0.009977,0.032235,0.8270,0.5025,0.7975,5.00,1.304020e-15,3.940800e-16,6.843000e-16,5.339840e-06,9.930000e-07,3.101760e-06
1,2.790,6.801840e-06,0.745800,4.400000,0.032960,0.000787,0.002708,0.003365,0.6545,0.7450,0.6230,3.25,7.992600e-15,3.529180e-15,5.807000e-15,1.347380e-05,5.993800e-06,9.818480e-06
2,9.318,6.801840e-06,0.745800,4.400000,0.003363,0.001348,0.001999,0.000726,0.8420,0.7556,0.8316,4.80,1.146900e-14,9.296600e-15,1.039080e-14,7.592200e-06,6.227740e-06,6.912200e-06
3,8.398,6.801840e-06,0.745800,4.400000,0.002410,0.001671,0.001732,0.000108,0.6964,0.6132,0.4800,1.00,1.105580e-14,8.676400e-15,9.865800e-15,6.858000e-06,5.502520e-06,6.178220e-06
4,8.654,6.801840e-06,0.745800,4.400000,0.001798,0.001588,0.001670,0.000074,0.7366,0.7500,0.3370,0.40,9.707600e-15,7.704400e-15,8.711000e-15,6.400200e-06,5.164380e-06,5.785660e-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2380,0.206,1.036533e-07,0.142333,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.016000e-15,0.000000e+00,0.000000e+00,2.776600e-06,0.000000e+00,3.796000e-07
2381,0.000,1.036533e-07,0.142333,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.803800e-07,0.000000e+00,0.000000e+00
2382,0.000,1.036533e-07,0.142333,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.749600e-07,0.000000e+00,0.000000e+00
2383,0.934,6.781333e-08,0.462333,1.666667,0.000133,0.000078,0.000086,0.000013,0.9010,0.5130,0.5050,1.00,2.209000e-16,3.178667e-17,1.039667e-16,1.567760e-07,2.735800e-08,7.326200e-08
2384,0.000,6.781333e-08,0.462333,1.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.237600e-06,0.000000e+00,0.000000e+00

Rescaling flux parameters

In [65]:
flux_params = ['photflux_aper' ,'photflux_aper_lolim' , 'photflux_aper_hilim' , 'flux_aper' , 'flux_aper_lolim' , 'flux_aper_hilim' ]
flux_params_model = ['flux_bb' , 'flux_bb_lolim' , 'flux_bb_hilim' , 'flux_brems' , 'flux_brems_hilim' , 'flux_brems_lolim' ,  'flux_powlaw' , 'flux_powlaw_lolim' , 'flux_powlaw_hilim' , ]
flux_params_band = []
for fp in flux_params:
    for f in filters:
        temp = fp+f
        flux_params_band.append(temp)
flux_params_extend = flux_params_band+flux_params

In [66]:
data_band_flux = data[flux_params_band] 
data_model_flux = data[flux_params_model].reset_index(drop=True)
data_band_flux = data_band_flux.reset_index(drop=True)
data_band_flux = data_band_flux.replace(0.0 , np.NAN)

display((data_band_flux))
data_mean_flux = data_band_mean[flux_params].reset_index(drop=True)
display(data_mean_flux)
data_flux = pd.concat([data_model_flux , data_mean_flux , data_band_flux] , axis=1)
data_flux = data_flux.replace(0 , np.nan)
data_flux = data_flux.replace('0' , np.nan)
data_flux = data_flux.replace('0.0' , np.nan)
display(data_flux)
data_flux.to_csv('temp.csv')

,photflux_aper_b,photflux_aper_h,photflux_aper_m,photflux_aper_u,photflux_aper_s,photflux_aper_lolim_b,photflux_aper_lolim_h,photflux_aper_lolim_m,photflux_aper_lolim_u,photflux_aper_lolim_s,...,flux_aper_lolim_b,flux_aper_lolim_h,flux_aper_lolim_m,flux_aper_lolim_u,flux_aper_lolim_s,flux_aper_hilim_b,flux_aper_hilim_h,flux_aper_hilim_m,flux_aper_hilim_u,flux_aper_hilim_s
0,4.409000e-06,NaN,7.348000e-07,0.000008,2.217000e-06,2.853000e-06,NaN,2.894000e-07,6.036000e-07,1.219000e-06,...,1.262000e-15,NaN,1.965000e-16,NaN,5.119000e-16,2.642000e-15,1.082000e-15,8.011000e-16,6.300000e-16,1.365000e-15
1,8.274000e-06,8.834000e-07,1.393000e-06,0.000035,3.852000e-06,6.333000e-06,3.480000e-07,7.960000e-07,1.983000e-05,2.662000e-06,...,4.108000e-15,6.079000e-16,7.010000e-16,1.024000e-14,1.989000e-15,6.668000e-15,2.634000e-15,1.723000e-15,2.517000e-14,3.768000e-15
2,1.319000e-05,1.131000e-06,1.442000e-06,0.000012,6.688000e-06,1.230000e-05,8.767000e-07,1.220000e-06,1.058000e-05,6.162000e-06,...,1.986000e-14,4.885000e-15,2.971000e-15,8.137000e-15,1.063000e-14,2.267000e-14,7.688000e-15,4.057000e-15,1.049000e-14,1.244000e-14
3,1.129000e-05,9.301000e-07,1.443000e-06,0.000012,5.518000e-06,1.045000e-05,6.976000e-07,1.209000e-06,1.014000e-05,5.016000e-06,...,1.780000e-14,4.769000e-15,2.943000e-15,9.212000e-15,8.658000e-15,2.070000e-14,8.016000e-15,4.083000e-15,1.209000e-14,1.039000e-14
4,1.104000e-05,9.253000e-07,1.238000e-06,0.000010,5.565000e-06,1.024000e-05,7.009000e-07,1.031000e-06,8.764000e-06,5.086000e-06,...,1.574000e-14,3.626000e-15,2.579000e-15,8.193000e-15,8.384000e-15,1.820000e-14,5.994000e-15,3.615000e-15,1.081000e-14,9.919000e-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2380,1.898000e-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.918000e-15,NaN,NaN,NaN,3.114000e-15
2381,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2383,1.972000e-07,NaN,5.181000e-08,NaN,1.173000e-07,8.011000e-08,NaN,9.010000e-09,NaN,4.767000e-08,...,NaN,NaN,2.347000e-17,NaN,7.189000e-17,1.398000e-16,NaN,2.464000e-16,NaN,2.765000e-16
2384,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,photflux_aper,photflux_aper_lolim,photflux_aper_hilim,flux_aper,flux_aper_lolim,flux_aper_hilim
0,3.101760e-06,9.930000e-07,5.339840e-06,6.843000e-16,3.940800e-16,1.304020e-15
1,9.818480e-06,5.993800e-06,1.347380e-05,5.807000e-15,3.529180e-15,7.992600e-15
2,6.912200e-06,6.227740e-06,7.592200e-06,1.039080e-14,9.296600e-15,1.146900e-14
3,6.178220e-06,5.502520e-06,6.858000e-06,9.865800e-15,8.676400e-15,1.105580e-14
4,5.785660e-06,5.164380e-06,6.400200e-06,8.711000e-15,7.704400e-15,9.707600e-15
...,...,...,...,...,...,...
2380,3.796000e-07,0.000000e+00,2.776600e-06,0.000000e+00,0.000000e+00,3.016000e-15
2381,0.000000e+00,0.000000e+00,7.803800e-07,NaN,NaN,NaN
2382,0.000000e+00,0.000000e+00,7.749600e-07,NaN,NaN,NaN
2383,7.326200e-08,2.735800e-08,1.567760e-07,1.039667e-16,3.178667e-17,2.209000e-16
2384,0.000000e+00,0.000000e+00,2.237600e-06,NaN,NaN,NaN

,flux_bb,flux_bb_lolim,flux_bb_hilim,flux_brems,flux_brems_hilim,flux_brems_lolim,flux_powlaw,flux_powlaw_lolim,flux_powlaw_hilim,photflux_aper,...,flux_aper_lolim_b,flux_aper_lolim_h,flux_aper_lolim_m,flux_aper_lolim_u,flux_aper_lolim_s,flux_aper_hilim_b,flux_aper_hilim_h,flux_aper_hilim_m,flux_aper_hilim_u,flux_aper_hilim_s
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.101760e-06,...,1.262000e-15,NaN,1.965000e-16,NaN,5.119000e-16,2.642000e-15,1.082000e-15,8.011000e-16,6.300000e-16,1.365000e-15
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.818480e-06,...,4.108000e-15,6.079000e-16,7.010000e-16,1.024000e-14,1.989000e-15,6.668000e-15,2.634000e-15,1.723000e-15,2.517000e-14,3.768000e-15
2,1.106000e-14,9.868000e-15,1.212000e-14,1.321000e-14,1.432000e-14,1.175000e-14,1.737000e-14,1.622000e-14,1.866000e-14,6.912200e-06,...,1.986000e-14,4.885000e-15,2.971000e-15,8.137000e-15,1.063000e-14,2.267000e-14,7.688000e-15,4.057000e-15,1.049000e-14,1.244000e-14
3,9.243000e-15,7.217000e-15,1.034000e-14,1.277000e-14,1.407000e-14,1.144000e-14,1.555000e-14,1.446000e-14,1.692000e-14,6.178220e-06,...,1.780000e-14,4.769000e-15,2.943000e-15,9.212000e-15,8.658000e-15,2.070000e-14,8.016000e-15,4.083000e-15,1.209000e-14,1.039000e-14
4,9.970000e-15,8.896000e-15,1.087000e-14,1.252000e-14,1.359000e-14,1.129000e-14,1.528000e-14,1.413000e-14,1.685000e-14,5.785660e-06,...,1.574000e-14,3.626000e-15,2.579000e-15,8.193000e-15,8.384000e-15,1.820000e-14,5.994000e-15,3.615000e-15,1.081000e-14,9.919000e-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.796000e-07,...,NaN,NaN,NaN,NaN,NaN,2.918000e-15,NaN,NaN,NaN,3.114000e-15
2381,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2383,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.326200e-08,...,NaN,NaN,2.347000e-17,NaN,7.189000e-17,1.398000e-16,NaN,2.464000e-16,NaN,2.765000e-16
2384,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
data_flux_log = pd.DataFrame()
for f in data_flux:
    temp = data_flux[f]
    temp = np.log10(temp)
#    display(temp)
    data_flux_log.insert(0 , f , temp)

display(data_flux_log)

,flux_aper_hilim_s,flux_aper_hilim_u,flux_aper_hilim_m,flux_aper_hilim_h,flux_aper_hilim_b,flux_aper_lolim_s,flux_aper_lolim_u,flux_aper_lolim_m,flux_aper_lolim_h,flux_aper_lolim_b,...,photflux_aper,flux_powlaw_hilim,flux_powlaw_lolim,flux_powlaw,flux_brems_lolim,flux_brems_hilim,flux_brems,flux_bb_hilim,flux_bb_lolim,flux_bb
0,-14.864867,-15.200659,-15.096313,-14.965773,-14.578067,-15.290815,NaN,-15.706637,NaN,-14.898941,...,-5.508392,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-14.423889,-13.599117,-14.763715,-14.579384,-14.176004,-14.701365,-13.989700,-15.154282,-15.216168,-14.386370,...,-5.007956,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-13.905180,-13.979225,-14.391795,-14.114187,-13.644548,-13.973467,-14.089536,-14.527097,-14.311135,-13.702021,...,-5.160384,-13.729088,-13.789949,-13.760200,-13.929962,-13.844057,-13.879097,-13.916497,-14.005771,-13.956245
3,-13.983384,-13.917574,-14.389021,-14.096042,-13.684030,-14.062582,-14.035646,-14.531210,-14.321573,-13.749580,...,-5.209137,-13.771600,-13.839832,-13.808270,-13.941574,-13.851706,-13.893809,-13.985479,-14.141643,-14.034187
4,-14.003532,-13.966174,-14.441892,-14.222283,-13.739929,-14.076549,-14.086557,-14.588549,-14.440572,-13.802995,...,-5.237647,-13.773400,-13.849858,-13.815877,-13.947306,-13.866781,-13.902396,-13.963770,-14.050805,-14.001305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2380,-14.506681,NaN,NaN,NaN,-14.534915,NaN,NaN,NaN,NaN,NaN,...,-6.420674,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2381,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2383,-15.558305,NaN,-15.608359,NaN,-15.854493,-16.143332,NaN,-16.629487,NaN,NaN,...,-7.135121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2384,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
var_params = [ 'var_index' ,'var_prob' , 'ks_prob' , 'kp_prob' ,'var_sigma' ,'var_mean' , 'var_min' ,  'var_max' , 'var_inter_index' , 'var_inter_prob' , 'var_inter_sigma']
data_var = data_band_mean[var_params].reset_index(drop=True)
display(data_var)

,var_index,var_prob,ks_prob,kp_prob,var_sigma,var_mean,var_min,var_max,var_inter_index,var_inter_prob,var_inter_sigma
0,5.00,0.7975,0.5025,0.8270,0.032235,0.009977,0.000461,0.514400,4.400000,0.745800,6.801840e-06
1,3.25,0.6230,0.7450,0.6545,0.003365,0.002708,0.000787,0.032960,4.400000,0.745800,6.801840e-06
2,4.80,0.8316,0.7556,0.8420,0.000726,0.001999,0.001348,0.003363,4.400000,0.745800,6.801840e-06
3,1.00,0.4800,0.6132,0.6964,0.000108,0.001732,0.001671,0.002410,4.400000,0.745800,6.801840e-06
4,0.40,0.3370,0.7500,0.7366,0.000074,0.001670,0.001588,0.001798,4.400000,0.745800,6.801840e-06
...,...,...,...,...,...,...,...,...,...,...,...
2380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.142333,1.036533e-07
2381,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.142333,1.036533e-07
2382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.142333,1.036533e-07
2383,1.00,0.5050,0.5130,0.9010,0.000013,0.000086,0.000078,0.000133,1.666667,0.462333,6.781333e-08
2384,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.666667,0.462333,6.781333e-08

In [69]:
single_params = [ 'flux_powlaw'  , 'powlaw_gamma' , 'powlaw_nh' ,  'powlaw_ampl' ,  'powlaw_stat' , 'bb_kt' , 'bb_nh' ,  'bb_ampl' ,  'bb_stat'  , 'brems_kt' , 'brems_nh' ,'brems_stat' ,]

hard_params = ['hard_hm' ,'hard_hm_hilim' ,'hard_hm_lolim' ,  'hard_hs' , 'hard_ms' ,'hard_hs_hilim' ,'hard_hs_lolim' ,'hard_ms_hilim' ,'hard_ms_lolim',]

model_fit_params = [ 'powlaw_gamma' , 'powlaw_gamma_hilim' , 'powlaw_gamma_lolim' ,'powlaw_nh' , 'powlaw_nh_hilim' , 'powlaw_nh_lolim' ,  'powlaw_ampl' ,  'powlaw_ampl_hilim' , 'powlaw_ampl_lolim' , 'powlaw_stat' , 'bb_kt' ,'bb_kt_hilim' , 'bb_kt_lolim' , 'bb_nh_hilim' , 'bb_nh_lolim' , 'bb_nh' ,  'bb_ampl' ,'bb_ampl_lolim' ,'bb_ampl_hilim' ,   'bb_stat' ,  'brems_kt' , 'brems_kt_hilim' ,'brems_kt_lolim' , 'brems_nh' , 'brems_nh_hilim' ,'brems_nh_lolim' ,'brems_stat' ,]

obs_info_params = [ 'livetime','significance','likelihood','pileup_flag','mstr_sat_src_flag','mstr_streak_src_flag'   ,'gti_obs' , 'flux_significance_b'  , 'flux_significance_m' , 'flux_significance_s' , 'flux_significance_h' , 'flux_significance_u'    ]

single_params_lim = [ ]

In [70]:
data_rest = data[hard_params+model_fit_params].reset_index(drop=True)
display(data_rest)

,hard_hm,hard_hm_hilim,hard_hm_lolim,hard_hs,hard_ms,hard_hs_hilim,hard_hs_lolim,hard_ms_hilim,hard_ms_lolim,powlaw_gamma,...,bb_ampl_lolim,bb_ampl_hilim,bb_stat,brems_kt,brems_kt_hilim,brems_kt_lolim,brems_nh,brems_nh_hilim,brems_nh_lolim,brems_stat
0,-0.2311,0.1468,-0.8688,-0.9994,-0.5334,-0.4703,-1.0000,-0.2430,-0.7651,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-0.1924,0.1318,-0.5141,-0.6384,-0.4922,-0.4229,-0.8151,-0.2867,-0.6690,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-0.1124,0.0144,-0.2417,-0.7096,-0.6458,-0.6527,-0.7639,-0.5965,-0.6952,2.853,...,0.001176,0.002441,3.983,0.6676,0.8101,0.5610,2.170000e-06,0.7779,NaN,5.962
3,-0.2086,-0.0718,-0.3492,-0.7108,-0.5871,-0.6452,-0.7726,-0.5253,-0.6452,2.707,...,0.000428,0.001075,4.074,0.9863,1.1950,0.7864,1.099000e-06,0.8403,NaN,1.909
4,-0.1412,-0.0031,-0.2804,-0.7146,-0.6346,-0.6527,-0.7739,-0.5790,-0.6889,2.517,...,0.000400,0.000759,3.526,1.0120,1.2480,0.8535,2.234000e-07,1.3290,NaN,3.019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2380,0.9994,1.0000,-0.1768,-0.9994,-0.9994,0.2392,-1.0000,0.0468,-1.0000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2381,0.9994,1.0000,-0.1318,0.9994,-0.9994,1.0000,-0.2367,1.0000,-1.0000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2382,0.9994,1.0000,-0.1768,0.9994,-0.9994,1.0000,-0.2592,1.0000,-1.0000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2383,-0.9994,-0.1405,-1.0000,-0.9994,-0.4035,-0.4728,-1.0000,-0.0019,-0.7427,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2384,0.9981,1.0000,-0.1730,0.9981,-0.9994,1.0000,-1.0000,0.3104,-1.0000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
data_obs_info = data[obs_info_params].reset_index(drop=True)
display(data_obs_info)

,livetime,significance,likelihood,pileup_flag,mstr_sat_src_flag,mstr_streak_src_flag,gti_obs,flux_significance_b,flux_significance_m,flux_significance_s,flux_significance_h,flux_significance_u
0,31673.8,29.48,5419.11600,False,False,False,2000-03-16T09:06:03,2.91,1.65,2.29,0.00,1.08
1,31670.6,29.48,5419.11600,False,False,False,2000-03-16T18:59:23,4.26,2.40,3.24,1.65,2.40
2,65237.5,29.48,5419.11600,False,False,False,2002-09-29T17:14:19,14.91,6.47,12.72,4.57,7.92
3,59044.6,29.48,5419.11600,False,False,False,2002-09-30T13:49:27,13.41,6.16,11.00,4.00,7.42
4,65240.7,29.48,5419.11600,False,False,False,2002-10-02T19:14:18,13.95,5.98,11.96,4.12,7.26
...,...,...,...,...,...,...,...,...,...,...,...,...
2380,1928.3,3.09,54.31331,False,False,False,2002-10-01T08:25:29,1.03,0.00,0.00,0.00,0.00
2381,5544.8,3.09,54.31331,False,False,False,2002-10-03T13:50:18,0.00,0.00,0.00,0.00,0.00
2382,5734.6,3.09,54.31331,False,False,False,2002-10-11T21:35:09,0.00,0.00,0.00,0.00,0.00
2383,68771.4,1.77,13.81354,False,False,False,2002-10-11T01:59:30,1.73,1.21,1.73,0.00,0.00
2384,1928.3,1.77,13.81354,False,False,False,2002-10-01T08:25:29,0.00,0.00,0.00,0.00,0.00

In [72]:
data_identify = data[['src_n' , 'src_id']].reset_index(drop=True)
print(data_identify)

                        src_n  src_id
0     CXOGLB J002353.9-720350  TC0001
1     CXOGLB J002353.9-720350  TC0001
2     CXOGLB J002353.9-720350  TC0001
3     CXOGLB J002353.9-720350  TC0001
4     CXOGLB J002353.9-720350  TC0001
...                       ...     ...
2380  CXOGLB J002437.1-720517  TC0273
2381  CXOGLB J002437.1-720517  TC0273
2382  CXOGLB J002437.1-720517  TC0273
2383  CXOGLB J002438.7-720427  TC0274
2384  CXOGLB J002438.7-720427  TC0274

[2385 rows x 2 columns]

In [56]:
data_combined = pd.concat([data_identify , data_obs_info , data_flux_log , data_var , data_rest] , axis=1)
obs_id = [src_class+'_OBS_'+str(i) for i in range(len(data_combined))]
data_combined.insert( 0 , 'obs_id' , obs_id)

data_combined.insert( 1 , 'class' , [src_class]*len(data_combined))
data_combined = data_combined.reset_index(drop=True)
data_combined.index.name = 'index'
display(data_combined)
data_combined.to_csv('../processed_data/'+src_class+'_.csv')

,obs_id,class,src_n,src_id,livetime,significance,likelihood,pileup_flag,mstr_sat_src_flag,mstr_streak_src_flag,...,bb_ampl_lolim,bb_ampl_hilim,bb_stat,brems_kt,brems_kt_hilim,brems_kt_lolim,brems_nh,brems_nh_hilim,brems_nh_lolim,brems_stat
index,,,,,,,,,,,,,,,,,,,,,
0,PULSAR_OBS_0,PULSAR,PSR J0007+7303,PL0001,49484.3,15.50,755.1790,False,False,False,...,0.000013,0.000018,3.025,95.300,4544.000,20.0500,0.661800,5.112,NaN,0.936
1,PULSAR_OBS_1,PULSAR,PSR J0023+0923,PL0002,3903.9,6.39,409.5469,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PULSAR_OBS_2,PULSAR,PSR J0023+0923,PL0002,12791.8,6.39,409.5469,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,PULSAR_OBS_3,PULSAR,PSR J0100-7211,PL0003,8372.1,65.51,39513.4200,False,False,False,...,0.001500,0.002073,0.754,1.100,1.248,0.9673,24.670000,29.310,20.46,0.581
4,PULSAR_OBS_4,PULSAR,PSR J0100-7211,PL0003,7165.7,65.51,39513.4200,False,False,False,...,0.001544,0.002336,1.096,1.024,1.212,0.8557,18.760000,26.500,11.96,0.618
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440,PULSAR_OBS_440,PULSAR,PSR J2229+6114,PL0133,93964.6,43.76,10080.5600,False,False,False,...,0.000020,0.000022,1.532,100.000,NaN,57.2400,36.040000,39.140,33.50,1.102
441,PULSAR_OBS_441,PULSAR,PSR J2238+5903,PL0134,9832.3,5.21,136.1509,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
442,PULSAR_OBS_442,PULSAR,PSR J2241-5236,PL0135,19930.0,8.23,425.7239,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
443,PULSAR_OBS_443,PULSAR,PSR J2256-1024,PL0136,19799.7,10.40,690.7692,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
444,PULSAR_OBS_444,PULSAR,PSR J2339-0533,PL0138,20871.4,16.48,1842.5340,False,False,False,...,0.000029,0.000040,3.121,68.910,569.600,21.8400,0.000045,5.508,NaN,1.394