In [3]:
import numpy as np 
import pandas as pd

In [17]:
src_class = 'NS'
frac = 0.9

In [18]:
data = pd.read_csv(src_class+'_data_clean_source_list.csv')
data =  data.sample(frac=1)
display(data.describe())
frac_no = int(len(data)*frac)
train_data = data.iloc[:frac_no]
test_data = data.iloc[frac_no:]
display(train_data)
display(test_data)
train_data.to_csv('final_list/'+src_class+'_train.csv')
test_data.to_csv('final_list/'+src_class+'_test.csv')

             A_RA       A_DEC        B_RA       B_DEC    XOFFSET_
count  118.000000  118.000000  118.000000  118.000000  118.000000
mean   193.874907  -31.548778  193.875218  -31.548815    0.047678
std    106.121899   34.363385  106.121580   34.363374    0.058420
min      7.262917  -73.443000    7.262675  -73.443001    0.000000
25%    100.094792  -60.439160  100.094958  -60.440200    0.010000
50%    256.452410  -30.625569  256.451901  -30.625751    0.021500
75%    267.731965  -18.142107  267.733912  -18.141775    0.059500
max    345.284583   64.828333  345.284506   64.828178    0.243000

,SRC_ID,A_NAME,A_RA,A_DEC,A_DATABASE_TABLE,A_OBSERVATORY,B_NAME,B_RA,B_DEC,XOFFSET_,DOWNLOADED
117,NS0118,XTE J1946+274,296.414000,27.365000,IBISCAT,INTEGRAL,2CXO J194539.3+272155,296.413911,27.365371,0.023,NaN
28,NS0029,2XMM J010337.4-720133,15.906000,-72.026130,XMMSSCLWBS,XMM-NEWTON,2CXO J010337.5-720133,15.906455,-72.025913,0.016,NaN
107,NS0108,SWIFT J1749.4-2807,267.382500,-28.134722,INTREFCAT,INTEGRAL,2CXO J174931.7-280805,267.382206,-28.134737,0.016,NaN
44,NS0045,2XMM J170942.6-442905,257.427580,-44.484950,XMMSSCLWBS,XMM-NEWTON,2CXO J170942.7-442908,257.428010,-44.485678,0.047,NaN
17,NS0018,2XMM J005044.8-731603,12.686570,-73.267780,XMMSSCLWBS,XMM-NEWTON,2CXO J005044.6-731605,12.686215,-73.268134,0.022,NaN
...,...,...,...,...,...,...,...,...,...,...,...
48,NS0049,2XMM J174906.8-273232,267.278290,-27.542320,XMMSSCLWBS,XMM-NEWTON,2CXO J174906.8-273233,267.278701,-27.542513,0.025,NaN
5,NS0006,1RXS J065948.1+141431,104.950417,14.241944,RASS2MASS,ROSAT,2CXO J065948.1+141421,104.950734,14.239219,0.165,NaN
114,NS0115,XTE J1710-281,257.551000,-28.132000,IBISCAT,INTEGRAL,2CXO J171012.5-280750,257.552347,-28.130798,0.101,NaN
27,NS0028,2XMM J010313.9-720914,15.808220,-72.154110,XMMSSCLWBS,XMM-NEWTON,2CXO J010313.9-720914,15.808059,-72.153974,0.009,NaN
113,NS0114,XTE J1709-267,257.377000,-26.656000,IBISCAT,INTEGRAL,2CXO J170930.3-263919,257.376621,-26.655548,0.034,NaN

,SRC_ID,A_NAME,A_RA,A_DEC,A_DATABASE_TABLE,A_OBSERVATORY,B_NAME,B_RA,B_DEC,XOFFSET_,DOWNLOADED
18,NS0019,2XMM J005152.0-731032,12.966250,-73.175720,XMMSSCLWBS,XMM-NEWTON,2CXO J005152.0-731034,12.966979,-73.176218,0.032,NaN
104,NS0105,SLX 1735-269,264.571000,-26.994000,IBISCAT,INTEGRAL,2CXO J173817.0-265939,264.571236,-26.994189,0.017,NaN
10,NS0011,1WGA J2301.1+5852,345.284583,58.879944,WGACAT,ROSAT,2CXO J230108.2+585244,345.284506,58.878949,0.060,NaN
55,NS0056,2XMM J185238.5+004020,283.160370,0.672180,XMMSSCLWBS,XMM-NEWTON,2CXO J185238.5+004019,283.160731,0.672130,0.022,NaN
96,NS0097,KS 1947+300,297.398000,30.209000,IBISCAT,INTEGRAL,2CXO J194935.4+301231,297.397762,30.208834,0.016,NaN
110,NS0111,XTE J0055-724,13.733642,-72.445898,XRBCAT,,2CXO J005456.2-722647,13.734239,-72.446658,0.047,NaN
103,NS0104,SAXWFC J1751.2-3037.7,267.791667,-30.628083,SAXWFCCAT,BEPPOSAX,2CXO J175110.6-303738,267.794242,-30.627472,0.138,NaN
30,NS0031,2XMM J053746.7-691017,84.444430,-69.171410,XMMSSCLWBS,XMM-NEWTON,2CXO J053747.4-691019,84.447521,-69.172182,0.081,NaN
50,NS0051,2XMM J175012.8-370306,267.552860,-37.051740,XMMSSCLWBS,XMM-NEWTON,2CXO J175012.7-370306,267.552922,-37.051758,0.003,NaN
83,NS0084,GRS 1741.9-2853,266.260000,-28.914000,IBISCAT,INTEGRAL,2CXO J174502.3-285449,266.259684,-28.913859,0.019,NaN
80,NS0081,E2259+587,345.282670,58.879437,XRBCAT,,2CXO J230108.2+585244,345.284506,58.878949,0.064,NaN
88,NS0089,IGR J17254-3257,261.353000,-32.954000,IBISCAT,INTEGRAL,2CXO J172524.9-325714,261.354147,-32.954104,0.058,NaN