## Data test train source split

In [25]:
# storing file names
import numpy as np 
import pandas as pd 

#src_class = input('BH/NS : ')
src_class = "CV"
frac = 1

data = pd.read_csv('source_list/'+src_class+'_data_clean_source_list.csv')
data =  data.sample(frac=1)
frac_no = int(len(data)*frac)
train_data = data.iloc[:frac_no]
test_data = data.iloc[frac_no:]
train_data.to_csv('source_list/final_list/'+src_class+'_train.csv')

import os
ctg = src_class

def hr():
    print('----------------------------------------------------------------------------')

# Copy sources data to respective folders

data = pd.read_csv('source_list/final_list/'+ctg+'_train.csv')
ch_names = [di.replace(' ' ,'_')[:-1] for di in data['B_NAME']]
a_names = [di.replace(' ' ,'_')[:-1]+'.csv' for di in data['A_NAME']]
src_id = [si[:6] for si in data['SRC_ID']]
#print(src_id)
os.system('rm -r '+ctg+'_data/train/')
os.system('mkdir '+ctg+'_data/train/')
for c,s ,a in zip(ch_names , src_id , a_names):
    try:
        src = '../data/all_data/'+ctg+'_data_all/'+c+'.csv' 
        ## adding source_id in file names
        dest = ctg+'_data/train/'+ s+'-'+c+'#'+a 
        #print('Copying' , c )
        os.system('cp '+src+' '+dest)
    except:
        hr()
        print('check source : ' , c )
        hr()

hr()
print('TRAINING DATA STORED')

----------------------------------------------------------------------------
TRAINING DATA STORED

## Append all data in one file

In [26]:
from ipywidgets import IntProgress
from IPython.display import display

src_class = src_class

def hr():
    print('_______________________________________________________________________________________')


def to_float(d):
    temp = []
    for di in d:
        
        try:
            temp.append(float(di))
        except Exception as e:
            print(e)
            print('NaN detected resetting value')
            temp.append(np.NAN)
    temp = np.asarray(temp)
    return temp

In [28]:
set_type = 'train'
os.system('ls '+src_class+'_data/'+set_type+'/ > file_list')
file_list = pd.read_csv('file_list' , names=['names'])['names']
data = pd.DataFrame()

for file in file_list:
    data_temp =  pd.read_csv(src_class+'_data/'+set_type+'/'+file)
    ## extracting source_id from file names 
    src_id_name = file[:6]
    src_id = [src_id_name]*len(data_temp)
    src_id = np.asarray(src_id)
    data_temp.insert(0 ,'src_id' , src_id)
    src_n_name = file[29:-4].replace('_' , ' ')
    src_n = [src_n_name]*len(data_temp)
    src_n = np.asarray(src_n)
    data_temp.insert(0 ,'src_n' , src_n)
    data =  data.append(data_temp)
data = data.replace('      NaN' , np.nan).reset_index(drop=True)
data.to_csv('raw_data/'+src_class+'_'+set_type+'.csv')
data.describe()

,index,sepn,ra,dec,obsid,obi,src_cnts_aper_h,src_cnts_aper_lolim_h,src_cnts_aper_hilim_h,gti_start,...,var_inter_sigma_s,var_inter_index_u,var_inter_prob_u,var_inter_sigma_u,acis_num,acis_hetg_num,acis_letg_num,hrc_num,hrc_hetg_num,hrc_letg_num
count,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,819.00000,819.000000,819.000000,8.200000e+02,...,5.590000e+02,417.000000,417.000000,4.150000e+02,820.000000,820.0,820.0,820.000000,820.0,820.0
mean,39.621951,0.001519,23.170944,-9.734346,6524.446341,0.125610,191.62338,185.608917,198.197861,2.463415e+08,...,1.055137e-05,3.798561,0.651890,2.518105e-05,57.151220,0.0,0.0,31.890244,0.0,0.0
std,39.281098,0.028638,57.681058,55.389392,4948.724248,0.389204,1334.64039,1320.543801,1348.325722,1.428472e+08,...,1.588067e-05,2.710857,0.421113,6.513088e-05,46.540558,0.0,0.0,31.585690,0.0,0.0
min,0.000000,0.000000,5.740186,-72.106040,78.000000,0.000000,0.00000,0.000000,0.996140,6.653411e+07,...,7.812000e-08,0.000000,0.000000,1.904000e-07,1.000000,0.0,0.0,0.000000,0.0,0.0
25%,4.000000,0.000000,6.029837,-72.079850,2736.000000,0.000000,0.00000,0.000000,1.240300,1.497069e+08,...,4.004000e-07,0.000000,0.203000,1.098000e-06,13.000000,0.0,0.0,0.000000,0.0,0.0
50%,12.000000,0.000000,10.629760,41.211880,4510.000000,0.000000,1.43860,0.077215,2.829000,1.847507e+08,...,2.864000e-06,5.000000,0.958000,2.285000e-06,23.000000,0.0,0.0,59.000000,0.0,0.0
75%,78.000000,0.000000,10.678240,41.267770,11279.000000,0.000000,40.01300,32.359500,47.447000,3.841864e+08,...,9.793000e-06,5.000000,1.000000,2.862000e-05,105.000000,0.0,0.0,63.000000,0.0,0.0
max,114.000000,0.819927,348.828800,61.685400,16561.000000,3.000000,17556.00000,17393.000000,17710.000000,5.058044e+08,...,8.416000e-05,8.000000,1.000000,4.943000e-04,109.000000,0.0,0.0,65.000000,0.0,0.0

# Data Processing

## Filtering

In [29]:
flag_params = ['streak_src_flag' , 'sat_src_flag' , 'pileup_flag' , 'mstr_sat_src_flag' , ]

In [30]:
def correct_bool(arr):
    temp = []
    #print(arr)
    for a in arr:
        #print(a , type(a))
        if(type(a) == bool):
            temp.append(a)
        else:
            if(a==' TRUE' or a=='True' or a=='  NAN'):
                temp.append(True)
            elif(a=='FALSE' or a=='False'):
                temp.append(False)
            else:
                print('something wrong' , a , type(a))
    return temp

In [31]:
def to_float(d):
    temp = []
    for di in d:
        
        try:
            temp.append(float(di))
        except Exception as e:
            print(e)
            print('NaN detected resetting value')
            temp.append(np.NAN)
    temp = np.asarray(temp)
    return temp

In [32]:
data = pd.read_csv('raw_data/'+src_class+'_'+set_type+'.csv' , index_col=0)
print('Data  Before flag filtering')
display(data.describe()[:1])
for f in flag_params:
    temp_flag = data[f]
    temp_flag = correct_bool(temp_flag)
    data[f] = temp_flag
    #print(temp_flag)
    data = data[data[f]==False]

#display(data)
data = data.dropna(how='all' , axis=1)
data = data.dropna(how='all' , axis=0)
display(data.describe()[:1])

Data  Before flag filtering

,index,sepn,ra,dec,obsid,obi,src_rate_aper_m,src_rate_aper_lolim_m,src_rate_aper_hilim_m,src_cnts_aper_u,...,var_inter_sigma_s,var_inter_index_u,var_inter_prob_u,var_inter_sigma_u,acis_num,acis_hetg_num,acis_letg_num,hrc_num,hrc_hetg_num,hrc_letg_num
count,820.0,820.0,820.0,820.0,820.0,820.0,782.0,782.0,782.0,812.0,...,559.0,417.0,417.0,415.0,820.0,820.0,820.0,820.0,820.0,820.0

,index,sepn,ra,dec,obsid,obi,src_rate_aper_m,src_rate_aper_lolim_m,src_rate_aper_hilim_m,src_cnts_aper_u,...,var_inter_sigma_s,var_inter_index_u,var_inter_prob_u,var_inter_sigma_u,acis_num,acis_hetg_num,acis_letg_num,hrc_num,hrc_hetg_num,hrc_letg_num
count,786.0,786.0,786.0,786.0,786.0,786.0,748.0,748.0,748.0,779.0,...,537.0,396.0,396.0,394.0,786.0,786.0,786.0,786.0,786.0,786.0

take average of Band params

In [33]:
band_params = [ 'photflux_aper' ,'photflux_aper_lolim' , 'photflux_aper_hilim' , 'flux_aper' , 'flux_aper_lolim' , 'flux_aper_hilim' , 'var_index' ,'var_prob' , 'ks_prob' , 'kp_prob' ,'var_sigma' ,'var_mean' , 'var_min' ,  'var_max' , 'var_inter_index' , 'var_inter_prob' , 'var_inter_sigma' , 'flux_significance']

filters = ['_b' ,'_h' ,'_m' ,'_u' ,'_s']

combining band parameterd

In [34]:
data_band_mean = pd.DataFrame()
data_band_mean.index.name = 'name'
for param in band_params[:]:
    temp_row = [param+f for f in filters]
    data_temp = data[temp_row][:]

    data_temp_new = pd.DataFrame()
    for j in data_temp:
        data_temp_new.insert( 0 ,j ,to_float(data_temp[j].to_numpy()))
    temp_mean =  data_temp_new.mean(axis=1)
    data_band_mean.insert(0 , param , temp_mean)

display(data_band_mean)
#data_band_mean.to_csv('temp.csv')

,flux_significance,var_inter_sigma,var_inter_prob,var_inter_index,var_max,var_min,var_mean,var_sigma,kp_prob,ks_prob,var_prob,var_index,flux_aper_hilim,flux_aper_lolim,flux_aper,photflux_aper_hilim,photflux_aper_lolim,photflux_aper
name,,,,,,,,,,,,,,,,,,
0,1.952,5.494375e-07,0.5155,3.0,0.007132,0.001035,0.001364,0.000773,0.864000,0.486500,0.597500,3.500000,1.910975e-14,8.332750e-15,1.381525e-14,0.000009,1.827300e-06,2.913000e-06
1,4.034,5.494375e-07,0.5155,3.0,0.001370,0.000624,0.000681,0.000088,0.569750,0.516500,0.477750,0.500000,2.650860e-14,4.847600e-15,6.340800e-15,0.000038,1.717600e-06,2.120000e-06
2,2.834,5.494375e-07,0.5155,3.0,0.001041,0.000520,0.000569,0.000074,0.774667,0.835667,0.548333,0.666667,6.222000e-15,2.607250e-15,4.227000e-15,0.000037,1.114640e-06,1.532480e-06
3,0.218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.170800e-15,0.000000e+00,0.000000e+00,0.000006,9.984000e-09,1.896800e-07
4,0.470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.197760e-14,4.053000e-16,3.441600e-15,0.000011,8.430000e-08,5.498600e-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
781,6.670,2.168140e-05,0.9572,5.8,0.025102,0.023768,0.024440,0.000624,0.403250,0.597250,0.215250,0.250000,2.650400e-13,1.953540e-13,2.201600e-13,0.000113,6.466200e-05,7.265800e-05
782,7.620,2.168140e-05,0.9572,5.8,0.031923,0.029982,0.030400,0.000435,0.236000,0.373500,0.143250,0.000000,3.626980e-13,2.930231e-13,3.282520e-13,0.000179,8.146460e-05,1.311940e-04
783,6.912,2.168140e-05,0.9572,5.8,0.028750,0.027585,0.028153,0.000570,0.363250,0.413250,0.178250,0.000000,3.168040e-13,2.518800e-13,2.818200e-13,0.000183,7.390400e-05,8.269800e-05
784,7.062,2.168140e-05,0.9572,5.8,0.026902,0.026615,0.026760,0.000130,0.298250,0.242750,0.110750,0.000000,3.179060e-13,2.408000e-13,2.702000e-13,0.000157,6.992800e-05,7.802600e-05
785,15.506,NaN,NaN,NaN,0.015720,0.007915,0.012339,0.003091,0.805200,0.849200,0.756200,4.600000,1.492064e-13,1.353060e-13,1.422420e-13,0.000043,3.573400e-05,3.914400e-05

Rescaling flux parameters

In [35]:
flux_params = ['photflux_aper' ,'photflux_aper_lolim' , 'photflux_aper_hilim' , 'flux_aper' , 'flux_aper_lolim' , 'flux_aper_hilim' ]
flux_params_model = ['flux_bb' , 'flux_bb_lolim' , 'flux_bb_hilim' , 'flux_brems' , 'flux_brems_hilim' , 'flux_brems_lolim' ,  'flux_powlaw' , 'flux_powlaw_lolim' , 'flux_powlaw_hilim' , ]
flux_params_band = []
for fp in flux_params:
    for f in filters:
        temp = fp+f
        flux_params_band.append(temp)
flux_params_extend = flux_params_band+flux_params

In [36]:
data_band_flux = data[flux_params_band] 
data_model_flux = data[flux_params_model].reset_index(drop=True)
data_band_flux = data_band_flux.reset_index(drop=True)
data_band_flux = data_band_flux.replace(0.0 , np.NAN)

display((data_band_flux))
data_mean_flux = data_band_mean[flux_params].reset_index(drop=True)
display(data_mean_flux)
data_flux = pd.concat([data_model_flux , data_mean_flux , data_band_flux] , axis=1)
data_flux = data_flux.replace(0 , np.nan)
data_flux = data_flux.replace('0' , np.nan)
data_flux = data_flux.replace('0.0' , np.nan)
display(data_flux)
data_flux.to_csv('temp.csv')

,photflux_aper_b,photflux_aper_h,photflux_aper_m,photflux_aper_u,photflux_aper_s,photflux_aper_lolim_b,photflux_aper_lolim_h,photflux_aper_lolim_m,photflux_aper_lolim_u,photflux_aper_lolim_s,...,flux_aper_lolim_b,flux_aper_lolim_h,flux_aper_lolim_m,flux_aper_lolim_u,flux_aper_lolim_s,flux_aper_hilim_b,flux_aper_hilim_h,flux_aper_hilim_m,flux_aper_hilim_u,flux_aper_hilim_s
0,0.000008,2.980000e-06,1.829000e-06,NaN,1.370000e-06,6.010000e-06,1.749000e-06,1.035000e-06,NaN,3.425000e-07,...,1.917000e-14,1.092000e-14,2.031000e-15,NaN,1.210000e-15,3.508000e-14,2.795000e-14,5.181000e-15,NaN,8.228000e-15
1,0.000006,1.706000e-06,1.500000e-06,NaN,1.616000e-06,4.988000e-06,1.336000e-06,1.197000e-06,NaN,1.067000e-06,...,1.286000e-14,6.353000e-15,2.802000e-15,NaN,2.223000e-15,1.806000e-14,1.123000e-14,4.183000e-15,9.380000e-14,5.270000e-15
2,0.000004,7.614000e-07,1.351000e-06,NaN,1.460000e-06,3.281000e-06,4.326000e-07,1.030000e-06,NaN,8.296000e-07,...,5.771000e-15,2.295000e-15,2.363000e-15,NaN,NaN,1.154000e-14,7.690000e-15,3.875000e-15,NaN,1.783000e-15
3,NaN,NaN,NaN,NaN,9.484000e-07,NaN,NaN,NaN,NaN,4.992000e-08,...,NaN,NaN,NaN,NaN,NaN,1.655000e-15,5.707000e-15,1.553000e-15,1.529000e-14,1.649000e-15
4,0.000002,NaN,7.203000e-07,NaN,NaN,3.529000e-07,NaN,6.860000e-08,NaN,NaN,...,1.275000e-15,5.681000e-16,1.834000e-16,NaN,NaN,1.338000e-14,1.477000e-14,3.575000e-15,2.636000e-14,1.803000e-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
781,0.000204,4.961000e-05,4.991000e-05,NaN,5.997000e-05,1.869000e-04,4.263000e-05,4.384000e-05,NaN,4.994000e-05,...,5.025000e-13,2.691000e-13,1.088000e-13,NaN,9.637000e-14,5.906000e-13,3.573000e-13,1.389000e-13,1.033000e-13,1.351000e-13
782,0.000253,7.716000e-05,5.818000e-05,0.000213,5.483000e-05,2.337000e-04,6.863000e-05,5.163000e-05,0.000008,4.516000e-05,...,7.465000e-13,5.071000e-13,1.284000e-13,7.254000e-16,8.239000e-14,8.666000e-13,6.371000e-13,1.609000e-13,3.119000e-14,1.177000e-13
783,0.000232,6.478000e-05,5.370000e-05,NaN,6.281000e-05,2.137000e-04,5.658000e-05,4.718000e-05,NaN,5.206000e-05,...,6.431000e-13,4.028000e-13,1.079000e-13,NaN,1.056000e-13,7.521000e-13,5.197000e-13,1.378000e-13,2.522000e-14,1.492000e-13
784,0.000219,4.684000e-05,5.877000e-05,NaN,6.592000e-05,2.017000e-04,4.020000e-05,5.230000e-05,NaN,5.544000e-05,...,6.197000e-13,2.927000e-13,1.345000e-13,NaN,1.571000e-13,7.240000e-13,3.895000e-13,1.678000e-13,9.173000e-14,2.165000e-13
785,0.000093,3.520000e-05,1.980000e-05,0.000026,2.165000e-05,8.958000e-05,3.317000e-05,1.853000e-05,0.000017,1.998000e-05,...,3.403000e-13,2.530000e-13,4.696000e-14,NaN,3.627000e-14,3.661000e-13,2.820000e-13,5.315000e-14,2.522000e-15,4.226000e-14

,photflux_aper,photflux_aper_lolim,photflux_aper_hilim,flux_aper,flux_aper_lolim,flux_aper_hilim
0,2.913000e-06,1.827300e-06,0.000009,1.381525e-14,8.332750e-15,1.910975e-14
1,2.120000e-06,1.717600e-06,0.000038,6.340800e-15,4.847600e-15,2.650860e-14
2,1.532480e-06,1.114640e-06,0.000037,4.227000e-15,2.607250e-15,6.222000e-15
3,1.896800e-07,9.984000e-09,0.000006,0.000000e+00,0.000000e+00,5.170800e-15
4,5.498600e-07,8.430000e-08,0.000011,3.441600e-15,4.053000e-16,1.197760e-14
...,...,...,...,...,...,...
781,7.265800e-05,6.466200e-05,0.000113,2.201600e-13,1.953540e-13,2.650400e-13
782,1.311940e-04,8.146460e-05,0.000179,3.282520e-13,2.930231e-13,3.626980e-13
783,8.269800e-05,7.390400e-05,0.000183,2.818200e-13,2.518800e-13,3.168040e-13
784,7.802600e-05,6.992800e-05,0.000157,2.702000e-13,2.408000e-13,3.179060e-13
785,3.914400e-05,3.573400e-05,0.000043,1.422420e-13,1.353060e-13,1.492064e-13

,flux_bb,flux_bb_lolim,flux_bb_hilim,flux_brems,flux_brems_hilim,flux_brems_lolim,flux_powlaw,flux_powlaw_lolim,flux_powlaw_hilim,photflux_aper,...,flux_aper_lolim_b,flux_aper_lolim_h,flux_aper_lolim_m,flux_aper_lolim_u,flux_aper_lolim_s,flux_aper_hilim_b,flux_aper_hilim_h,flux_aper_hilim_m,flux_aper_hilim_u,flux_aper_hilim_s
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.913000e-06,...,1.917000e-14,1.092000e-14,2.031000e-15,NaN,1.210000e-15,3.508000e-14,2.795000e-14,5.181000e-15,NaN,8.228000e-15
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.120000e-06,...,1.286000e-14,6.353000e-15,2.802000e-15,NaN,2.223000e-15,1.806000e-14,1.123000e-14,4.183000e-15,9.380000e-14,5.270000e-15
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.532480e-06,...,5.771000e-15,2.295000e-15,2.363000e-15,NaN,NaN,1.154000e-14,7.690000e-15,3.875000e-15,NaN,1.783000e-15
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.896800e-07,...,NaN,NaN,NaN,NaN,NaN,1.655000e-15,5.707000e-15,1.553000e-15,1.529000e-14,1.649000e-15
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.498600e-07,...,1.275000e-15,5.681000e-16,1.834000e-16,NaN,NaN,1.338000e-14,1.477000e-14,3.575000e-15,2.636000e-14,1.803000e-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
781,3.897000e-13,3.420000e-13,4.331000e-13,4.913000e-13,5.515000e-13,4.070000e-13,5.124000e-13,4.619000e-13,5.620000e-13,7.265800e-05,...,5.025000e-13,2.691000e-13,1.088000e-13,NaN,9.637000e-14,5.906000e-13,3.573000e-13,1.389000e-13,1.033000e-13,1.351000e-13
782,5.761000e-13,5.201000e-13,6.258000e-13,6.451000e-13,7.072000e-13,5.086000e-13,6.592000e-13,5.943000e-13,7.212000e-13,1.311940e-04,...,7.465000e-13,5.071000e-13,1.284000e-13,7.254000e-16,8.239000e-14,8.666000e-13,6.371000e-13,1.609000e-13,3.119000e-14,1.177000e-13
783,4.077000e-13,3.648000e-13,4.532000e-13,5.437000e-13,5.937000e-13,4.499000e-13,5.547000e-13,4.990000e-13,6.139000e-13,8.269800e-05,...,6.431000e-13,4.028000e-13,1.079000e-13,NaN,1.056000e-13,7.521000e-13,5.197000e-13,1.378000e-13,2.522000e-14,1.492000e-13
784,3.676000e-13,3.156000e-13,4.144000e-13,5.254000e-13,5.803000e-13,4.319000e-13,5.318000e-13,4.823000e-13,5.863000e-13,7.802600e-05,...,6.197000e-13,2.927000e-13,1.345000e-13,NaN,1.571000e-13,7.240000e-13,3.895000e-13,1.678000e-13,9.173000e-14,2.165000e-13
785,2.556000e-13,2.409000e-13,2.679000e-13,3.072000e-13,3.195000e-13,2.926000e-13,3.179000e-13,3.040000e-13,3.315000e-13,3.914400e-05,...,3.403000e-13,2.530000e-13,4.696000e-14,NaN,3.627000e-14,3.661000e-13,2.820000e-13,5.315000e-14,2.522000e-15,4.226000e-14

In [41]:
data_flux_log = pd.DataFrame()
for f in data_flux:
    temp = data_flux[f]
    temp = np.log10(temp)
#    display(temp)
    data_flux_log.insert(0 , f , temp)

display(data_flux_log)

,flux_aper_hilim_s,flux_aper_hilim_u,flux_aper_hilim_m,flux_aper_hilim_h,flux_aper_hilim_b,flux_aper_lolim_s,flux_aper_lolim_u,flux_aper_lolim_m,flux_aper_lolim_h,flux_aper_lolim_b,...,photflux_aper,flux_powlaw_hilim,flux_powlaw_lolim,flux_powlaw,flux_brems_lolim,flux_brems_hilim,flux_brems,flux_bb_hilim,flux_bb_lolim,flux_bb
0,-14.084706,NaN,-14.285586,-13.553618,-13.454940,-14.917215,NaN,-14.692290,-13.961777,-13.717378,...,-5.535660,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-14.278189,-13.027797,-14.378512,-13.949620,-13.743282,-14.653061,NaN,-14.552532,-14.197021,-13.890759,...,-5.673664,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-14.748849,NaN,-14.411728,-14.114074,-13.937794,NaN,NaN,-14.626536,-14.639217,-14.238749,...,-5.814605,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-14.782779,-13.815593,-14.808829,-14.243592,-14.781202,NaN,NaN,NaN,NaN,NaN,...,-6.721978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-14.744004,-13.579055,-14.446724,-13.830620,-13.873544,NaN,NaN,-15.736601,-15.245575,-14.894490,...,-6.259748,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
781,-12.869345,-12.985900,-12.857298,-12.446967,-12.228707,-13.016058,NaN,-12.963371,-12.570086,-12.298864,...,-4.138717,-12.250264,-12.335452,-12.290391,-12.390406,-12.258454,-12.308653,-12.363412,-12.465974,-12.409270
782,-12.929224,-13.505985,-12.793444,-12.195792,-12.062181,-13.084125,-15.139422,-12.891435,-12.294906,-12.126970,...,-3.882086,-12.141944,-12.225994,-12.180983,-12.293624,-12.150458,-12.190373,-12.203564,-12.283913,-12.239502
783,-12.826231,-13.598255,-12.860751,-12.284247,-12.123724,-12.976336,NaN,-12.966979,-12.394911,-12.191721,...,-4.082505,-12.211902,-12.301899,-12.255942,-12.346884,-12.226433,-12.264641,-12.343710,-12.437945,-12.389659
784,-12.664542,-13.037489,-12.775208,-12.409493,-12.140261,-12.803824,NaN,-12.871278,-12.533577,-12.207819,...,-4.107761,-12.231880,-12.316683,-12.274252,-12.364617,-12.236347,-12.279510,-12.382580,-12.500863,-12.434624
785,-13.374071,-14.598255,-13.274497,-12.549751,-12.436400,-13.440452,NaN,-13.328272,-12.596879,-12.468138,...,-4.407335,-12.479516,-12.517126,-12.497709,-12.533726,-12.495529,-12.512579,-12.572027,-12.618163,-12.592439

In [42]:
var_params = [ 'var_index' ,'var_prob' , 'ks_prob' , 'kp_prob' ,'var_sigma' ,'var_mean' , 'var_min' ,  'var_max' , 'var_inter_index' , 'var_inter_prob' , 'var_inter_sigma']
data_var = data_band_mean[var_params].reset_index(drop=True)
display(data_var)

,var_index,var_prob,ks_prob,kp_prob,var_sigma,var_mean,var_min,var_max,var_inter_index,var_inter_prob,var_inter_sigma
0,3.500000,0.597500,0.486500,0.864000,0.000773,0.001364,0.001035,0.007132,3.0,0.5155,5.494375e-07
1,0.500000,0.477750,0.516500,0.569750,0.000088,0.000681,0.000624,0.001370,3.0,0.5155,5.494375e-07
2,0.666667,0.548333,0.835667,0.774667,0.000074,0.000569,0.000520,0.001041,3.0,0.5155,5.494375e-07
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
781,0.250000,0.215250,0.597250,0.403250,0.000624,0.024440,0.023768,0.025102,5.8,0.9572,2.168140e-05
782,0.000000,0.143250,0.373500,0.236000,0.000435,0.030400,0.029982,0.031923,5.8,0.9572,2.168140e-05
783,0.000000,0.178250,0.413250,0.363250,0.000570,0.028153,0.027585,0.028750,5.8,0.9572,2.168140e-05
784,0.000000,0.110750,0.242750,0.298250,0.000130,0.026760,0.026615,0.026902,5.8,0.9572,2.168140e-05
785,4.600000,0.756200,0.849200,0.805200,0.003091,0.012339,0.007915,0.015720,NaN,NaN,NaN

In [43]:
single_params = [ 'flux_powlaw'  , 'powlaw_gamma' , 'powlaw_nh' ,  'powlaw_ampl' ,  'powlaw_stat' , 'bb_kt' , 'bb_nh' ,  'bb_ampl' ,  'bb_stat'  , 'brems_kt' , 'brems_nh' ,'brems_stat' ,]

hard_params = ['hard_hm' ,'hard_hm_hilim' ,'hard_hm_lolim' ,  'hard_hs' , 'hard_ms' ,'hard_hs_hilim' ,'hard_hs_lolim' ,'hard_ms_hilim' ,'hard_ms_lolim',]

model_fit_params = [ 'powlaw_gamma' , 'powlaw_gamma_hilim' , 'powlaw_gamma_lolim' ,'powlaw_nh' , 'powlaw_nh_hilim' , 'powlaw_nh_lolim' ,  'powlaw_ampl' ,  'powlaw_ampl_hilim' , 'powlaw_ampl_lolim' , 'powlaw_stat' , 'bb_kt' ,'bb_kt_hilim' , 'bb_kt_lolim' , 'bb_nh_hilim' , 'bb_nh_lolim' , 'bb_nh' ,  'bb_ampl' ,'bb_ampl_lolim' ,'bb_ampl_hilim' ,   'bb_stat' ,  'brems_kt' , 'brems_kt_hilim' ,'brems_kt_lolim' , 'brems_nh' , 'brems_nh_hilim' ,'brems_nh_lolim' ,'brems_stat' ,]

obs_info_params = [ 'livetime','significance','likelihood','pileup_flag','mstr_sat_src_flag','mstr_streak_src_flag'   ,'gti_obs' , 'flux_significance_b'  , 'flux_significance_m' , 'flux_significance_s' , 'flux_significance_h' , 'flux_significance_u'    ]

single_params_lim = [ ]

In [44]:
data_rest = data[hard_params+model_fit_params].reset_index(drop=True)
display(data_rest)

,hard_hm,hard_hm_hilim,hard_hm_lolim,hard_hs,hard_ms,hard_hs_hilim,hard_hs_lolim,hard_ms_hilim,hard_ms_lolim,powlaw_gamma,...,bb_ampl_lolim,bb_ampl_hilim,bb_stat,brems_kt,brems_kt_hilim,brems_kt_lolim,brems_nh,brems_nh_hilim,brems_nh_lolim,brems_stat
0,0.2611,0.5103,-0.0194,0.3260,0.0462,0.6465,-0.0069,0.4279,-0.2942,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0737,0.2130,-0.0731,0.0025,-0.0725,0.2067,-0.1843,0.1305,-0.2492,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-0.2661,-0.0556,-0.4878,-0.3648,-0.0899,-0.0893,-0.6015,0.1555,-0.3004,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.9981,1.0000,-0.3067,-0.9994,-0.9994,-0.2067,-1.0000,-0.2780,-1.0000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.1999,0.6215,-0.5840,0.9994,-0.0612,1.0000,-0.3167,0.6964,-0.5041,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
781,0.0012,0.0918,-0.0906,-0.0987,-0.0999,0.0106,-0.2017,0.0044,-0.1980,2.071,...,0.000228,0.000440,2.256,4.334,6.475,3.119,5.096,13.680,NaN,0.465
782,0.1449,0.2205,0.0668,0.1674,0.0225,0.2680,0.0681,0.1268,-0.0793,1.858,...,0.000159,0.000250,1.666,6.150,10.270,4.217,18.220,28.940,8.972,0.861
783,0.0949,0.1793,0.0094,0.0100,-0.0849,0.1156,-0.0918,0.0194,-0.1855,1.846,...,0.000225,0.000392,2.444,6.490,12.520,4.064,5.549,14.910,NaN,0.942
784,-0.1087,-0.0231,-0.1968,-0.1711,-0.0625,-0.0681,-0.2705,0.0344,-0.1555,2.132,...,0.000348,0.000713,2.843,4.340,6.583,3.066,6.158,14.240,NaN,0.847
785,0.2811,0.3179,0.2430,0.2386,-0.0462,0.2829,0.1955,0.0031,-0.0931,1.090,...,0.000038,0.000046,2.473,100.000,NaN,68.990,7.018,9.602,4.625,0.977

In [45]:
data_obs_info = data[obs_info_params].reset_index(drop=True)
display(data_obs_info)

,livetime,significance,likelihood,pileup_flag,mstr_sat_src_flag,mstr_streak_src_flag,gti_obs,flux_significance_b,flux_significance_m,flux_significance_s,flux_significance_h,flux_significance_u
0,9841.8,9.81,250.012,False,False,False,2001-09-05T00:24:13,3.53,2.36,1.38,2.49,0.00
1,66285.9,9.81,250.012,False,False,False,2011-09-04T06:26:17,7.53,5.09,2.94,4.61,0.00
2,52365.0,9.81,250.012,False,False,False,2011-08-29T18:50:48,5.20,4.21,2.38,2.38,0.00
3,4903.5,37.03,4392.422,False,False,False,2002-08-11T18:17:21,0.00,0.00,1.09,0.00,0.00
4,4108.6,37.03,4392.422,False,False,False,2004-09-02T14:31:38,1.21,1.14,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...
781,3907.5,174.76,172643.300,False,False,False,2013-06-26T09:48:40,12.05,8.23,5.97,7.10,0.00
782,3907.5,174.76,172643.300,False,False,False,2013-07-24T02:41:33,13.43,8.89,5.67,9.05,1.06
783,3907.5,174.76,172643.300,False,False,False,2013-08-26T10:03:03,12.59,8.23,5.84,7.90,0.00
784,3974.2,174.76,172643.300,False,False,False,2013-09-27T14:10:38,12.89,9.08,6.29,7.05,0.00
785,30178.9,27.61,5192.965,False,False,False,2014-01-11T05:14:05,27.61,16.13,12.97,17.82,3.00

In [46]:
data_identify = data[['src_n' , 'src_id']].reset_index(drop=True)
print(data_identify)

                      src_n  src_id
0    [DSH2013] 24            CV0001
1    [DSH2013] 24            CV0001
2    [DSH2013] 24            CV0001
3    [HPH2013] 100           CV0002
4    [HPH2013] 100           CV0002
..                      ...     ...
781  XMMSL2 J004231.9+41162  CV0110
782  XMMSL2 J004231.9+41162  CV0110
783  XMMSL2 J004231.9+41162  CV0110
784  XMMSL2 J004231.9+41162  CV0110
785  XSS J12270-4859         CV0112

[786 rows x 2 columns]

In [49]:
data_combined = pd.concat([data_identify , data_obs_info , data_flux_log , data_var , data_rest] , axis=1)
obs_id = [src_class+'_OBS_'+str(i) for i in range(len(data_combined))]
data_combined.insert( 0 , 'obs_id' , obs_id)

data_combined.insert( 1 , 'class' , [src_class]*len(data_combined))
data_combined = data_combined.reset_index(drop=True)
data_combined.index.name = 'index'
display(data_combined)
data_combined.to_csv('../processed_data/'+src_class+'_.csv')

,obs_id,class,src_n,src_id,livetime,significance,likelihood,pileup_flag,mstr_sat_src_flag,mstr_streak_src_flag,...,bb_ampl_lolim,bb_ampl_hilim,bb_stat,brems_kt,brems_kt_hilim,brems_kt_lolim,brems_nh,brems_nh_hilim,brems_nh_lolim,brems_stat
index,,,,,,,,,,,,,,,,,,,,,
0,CV_OBS_0,CV,[DSH2013] 24,CV0001,9841.8,9.81,250.012,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CV_OBS_1,CV,[DSH2013] 24,CV0001,66285.9,9.81,250.012,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CV_OBS_2,CV,[DSH2013] 24,CV0001,52365.0,9.81,250.012,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CV_OBS_3,CV,[HPH2013] 100,CV0002,4903.5,37.03,4392.422,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CV_OBS_4,CV,[HPH2013] 100,CV0002,4108.6,37.03,4392.422,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
781,CV_OBS_781,CV,XMMSL2 J004231.9+41162,CV0110,3907.5,174.76,172643.300,False,False,False,...,0.000228,0.000440,2.256,4.334,6.475,3.119,5.096,13.680,NaN,0.465
782,CV_OBS_782,CV,XMMSL2 J004231.9+41162,CV0110,3907.5,174.76,172643.300,False,False,False,...,0.000159,0.000250,1.666,6.150,10.270,4.217,18.220,28.940,8.972,0.861
783,CV_OBS_783,CV,XMMSL2 J004231.9+41162,CV0110,3907.5,174.76,172643.300,False,False,False,...,0.000225,0.000392,2.444,6.490,12.520,4.064,5.549,14.910,NaN,0.942
784,CV_OBS_784,CV,XMMSL2 J004231.9+41162,CV0110,3974.2,174.76,172643.300,False,False,False,...,0.000348,0.000713,2.843,4.340,6.583,3.066,6.158,14.240,NaN,0.847
785,CV_OBS_785,CV,XSS J12270-4859,CV0112,30178.9,27.61,5192.965,False,False,False,...,0.000038,0.000046,2.473,100.000,NaN,68.990,7.018,9.602,4.625,0.977